# - name: delete app directory
#   ansible.builtin.file:
#    path: "{{ app_location }}"
#    state: absent
#   # ignore-errors:yes

# - name: create app directory  
#   ansible.builtin.file:
#    path: "{{ app_location }}"
#    state: directory

# # - name: download and extract code
# #   ansible.builtin.get_url:
# #    url: " https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ component }}-v2.zip"  
# #    dest: /tmp/backend.zip
# #    dest: "{{ app_location }}"
# #    remotte_src: yes
# # - name: download code
# #   ansible.builtin.get_url:
# #     url: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ component }}-v2.zip"
# #     dest: /tmp/{{ component }}.zip 

# - name: extract code
#   ansible.builtin.unarchive:
#     src: /tmp/{{ component }}.zip
#     dest: "{{ app_location }}"
#     remote_src: yes

- name: remove existing directory
  tags: 
  - deployment
  ansible.builtin.file:
    path: "{{ app_location }}" # backend folder is /app, frontend /usr/share/nginx/html
    state: absent

- name: create app directory
  tags: 
  - deployment
  ansible.builtin.file:
    path: "{{ app_location }}" # backend folder is /app, frontend /usr/share/nginx/html
    state: directory

- name: download app code
  tags: 
  - deployment
  ansible.builtin.unarchive:
    src: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ COMPONENT }}-v2.zip"
    dest: "{{ app_location }}"
    remote_src: yes